version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: srms-postgres
    restart: always
    environment:
      POSTGRES_DB: srmsdb
      POSTGRES_USER: srms
      POSTGRES_PASSWORD: srmsdbpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
